"""Command line for the forecast archive and verification.

Deliberately separate from ``atlas.cli``: the daily pipeline and the site build
are untouched by this work, and nothing here runs as part of them.

    atlas-forecast backfill      pull Previous Runs history into the archive
    atlas-forecast live          append the forecast as issued now
    atlas-forecast verify        pair with truth and write the findings report

Every number in the report comes from ``verify``, so any figure quoted anywhere
can be regenerated by running it again.
"""

from __future__ import annotations

import argparse
from datetime import date, datetime, timedelta, timezone
from pathlib import Path

import pandas as pd

from atlas.config import AtlasConfig, load_config
from atlas.forecast_archive import (
    ATTRIBUTION,
    CallBudget,
    availability_report,
    backfill_previous_runs,
    fetch_live_forecast,
    read_archive,
    write_archive,
)
from atlas.forecast_verification import (
    IRRADIANCE_VARIABLES,
    STATION_EQUIVALENTS,
    build_truth_table,
    clear_sky_index,
    irradiance_caveat,
    pair_forecasts_with_truth,
    score,
)
from atlas.cams import SNOW_CAVEAT, CamsCredentialError, fetch_cams_radiation
from atlas.hungaromet import fetch_station_history, fetch_station_observations
from atlas.ingest import fetch_open_meteo_period

REPORT_PATH = Path("docs/forecast_verification.md")


def _load_truth(config: AtlasConfig, start: date, end: date, refresh: bool) -> tuple[pd.DataFrame, list[str]]:
    """Station history plus the current year, with ERA5 available for the gaps."""
    notes: list[str] = []
    history = fetch_station_history(config, refresh=refresh)
    # The recent file holds only the current calendar year, so asking it for the
    # whole span would report a meaningless 24% coverage figure.
    recent_start = max(start, date(end.year, 1, 1))
    recent = fetch_station_observations(config, recent_start, end, refresh=refresh)
    notes.extend(history.notes)
    notes.extend(recent.notes)

    frames = [frame for frame in (history.frame, recent.frame) if not frame.empty]
    combined = history
    if frames:
        merged = (
            pd.concat(frames, ignore_index=True)
            .drop_duplicates(subset=["time"], keep="last")
            .sort_values("time")
            .reset_index(drop=True)
        )
        combined = type(history)(merged, history.station_id, history.station_name, [])

    era5 = pd.DataFrame()
    try:
        era5 = fetch_open_meteo_period(config, start, end, refresh=refresh)
    except Exception as exc:  # pragma: no cover - network dependent
        notes.append(f"ERA5 fallback unavailable: {exc}")

    cams = pd.DataFrame()
    try:
        radiation = fetch_cams_radiation(config, start, end, refresh=refresh)
        cams = radiation.frame
        notes.extend(radiation.notes)
    except CamsCredentialError as exc:
        # Actionable, and the run continues on ERA5 with the weaker label rather
        # than failing outright.
        notes.append(f"CAMS irradiance truth unavailable: {exc}")
    except Exception as exc:  # pragma: no cover - network dependent
        notes.append(f"CAMS irradiance truth unavailable: {exc}")

    truth, truth_notes = build_truth_table(combined, era5, cams)
    notes.extend(truth_notes)
    return truth, notes


def _table(frame: pd.DataFrame, floats: int = 3) -> str:
    """Render a markdown table without pulling in tabulate for six lines of work."""
    if frame.empty:
        return "_No rows._"
    formatted = frame.copy()
    for column in formatted.select_dtypes("float"):
        formatted[column] = formatted[column].round(floats)
    header = [str(column) for column in formatted.columns]
    rows = [[("" if pd.isna(cell) else str(cell)) for cell in record] for record in formatted.to_numpy()]
    lines = ["| " + " | ".join(header) + " |", "|" + "|".join(["---"] * len(header)) + "|"]
    lines.extend("| " + " | ".join(row) + " |" for row in rows)
    return "\n".join(lines)


def command_backfill(config: AtlasConfig, args: argparse.Namespace) -> None:
    settings = config.forecast_archive
    start = date.fromisoformat(args.start or settings.start_date)
    end = date.fromisoformat(args.end) if args.end else datetime.now(timezone.utc).date() - timedelta(days=1)
    budget = CallBudget(delay_seconds=settings.request_delay_seconds)
    print(f"Backfilling {start} to {end}; leads {settings.lead_days}; models {settings.models}")
    frame, budget = backfill_previous_runs(
        config, start=start, end=end, budget=budget, refresh=args.refresh
    )
    paths = write_archive(config, frame, "backfill")
    print(f"Rows: {len(frame):,}; parquet files: {len(paths)}")
    print(f"Budget: {budget.summary()}")


def command_live(config: AtlasConfig, args: argparse.Namespace) -> None:
    frame, budget = fetch_live_forecast(config, forecast_days=args.forecast_days, refresh=args.refresh)
    paths = write_archive(config, frame, "live")
    print(f"Rows: {len(frame):,}; parquet files: {len(paths)}")
    print(f"Budget: {budget.summary()}")


def command_verify(config: AtlasConfig, args: argparse.Namespace) -> None:
    forecasts = read_archive(config, args.kind)
    if forecasts.empty:
        print("The archive is empty; run backfill first.")
        return

    start = forecasts["valid_time_utc"].min().date()
    end = forecasts["valid_time_utc"].max().date()
    truth, notes = _load_truth(config, start, end, refresh=args.refresh)
    result = pair_forecasts_with_truth(forecasts, truth)
    notes.extend(result.notes)
    if not result.available:
        print("No forecast-observation pairs were produced.")
        for note in notes:
            print(" -", note)
        return

    pairs = result.pairs
    # The label has to match the truth actually used, not the truth intended.
    irradiance_pairs = pairs[pairs["variable"].isin(IRRADIANCE_VARIABLES)]
    caveat = irradiance_caveat(irradiance_pairs["truth_source"].unique())
    irradiance_context = (
        SNOW_CAVEAT
        if "cams" in set(irradiance_pairs["truth_source"].unique())
        else "ERA5 is model output. A correction trained toward it measures agreement "
        "between two models, not skill against reality."
    )
    # Station-only unless a variable has no station equivalent at all, so headline
    # scores are not quietly propped up by reanalysis.
    station_pairs = pairs[pairs["truth_source"] == "station"]

    lines: list[str] = []
    lines.append("# Forecast verification: raw NWP error at Debrecen")
    lines.append("")
    lines.append(
        f"Generated by `atlas-forecast verify` on "
        f"{datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}. "
        "Stage 1 only: no correction is fitted and no value is adjusted."
    )
    lines.append("")
    lines.append(
        f"> **Irradiance ({', '.join(sorted(IRRADIANCE_VARIABLES))}) is {caveat}.** "
        + irradiance_context
    )
    lines.append("")
    lines.append("## Attribution")
    lines.append("")
    lines.append(ATTRIBUTION)
    lines.append("")
    lines.append("## Coverage")
    lines.append("")
    lines.append(f"- Archive rows: {len(forecasts):,}")
    lines.append(f"- Paired rows: {len(pairs):,}")
    lines.append(f"- Station-truth pairs: {len(station_pairs):,}")
    lines.append(f"- ERA5-fallback pairs: {len(pairs) - len(station_pairs):,}")
    lines.append(f"- Valid time span: {pairs['valid_time_utc'].min()} to {pairs['valid_time_utc'].max()}")
    lines.append("")
    for note in notes:
        lines.append(f"- {note}")
    lines.append("")

    lines.append("## Data quality")
    lines.append("")
    # Structural fallback (no station channel at all) versus real station gaps.
    station_capable = pairs[pairs["variable"].isin(STATION_EQUIVALENTS)]
    if not station_capable.empty:
        gaps = int((station_capable["truth_source"] == "era5").sum())
        lines.append(
            f"- Of the {len(station_capable):,} pairs for variables the station actually measures, "
            f"{gaps:,} ({gaps / len(station_capable):.2%}) fall back to ERA5. The remaining "
            "fallback in the totals above is structural: the HungaroMet 10-minute export carries "
            "no radiation or cloud channel, so those variables can only be verified against ERA5."
        )
    lines.append(
        "- **Pre-existing caching bug found in `fetch_station_observations`.** Its cache key is "
        "`station_<id>_<start.year>.zip`, but the URL is a single rolling `recent` file with no "
        "year in it. The same resource is therefore stored under several names at different "
        "vintages, and the `start` year silently selects which vintage is read. Verifying with "
        "one year's key returned station data ending 2026-07-30 while another key held data to "
        "2026-08-18. Run `--refresh` to be sure of the vintage. Not fixed here: it lives in the "
        "daily pipeline, which stage 1 does not touch."
    )
    # Model/variable combinations the provider does not carry at all.
    present = set(map(tuple, forecasts[["variable", "model"]].drop_duplicates().to_numpy()))
    for variable in sorted(forecasts["variable"].unique()):
        absent = [m for m in config.forecast_archive.models if (variable, m) not in present]
        if absent:
            lines.append(f"- `{variable}` is not available from {', '.join(absent)} and is absent for it.")
    # Error should grow with lead time; anything else is worth suspicion.
    monotonic = score(station_pairs, ["variable", "model", "lead_time_hours"])
    for (variable, model), group in monotonic.groupby(["variable", "model"], observed=True):
        ordered = group.sort_values("lead_time_hours")
        if len(ordered) > 1 and ordered["mae"].iloc[0] > ordered["mae"].iloc[-1]:
            lines.append(
                f"- **{variable} / {model}**: MAE at 24 h ({ordered['mae'].iloc[0]:.3f}) exceeds "
                f"MAE at {int(ordered['lead_time_hours'].iloc[-1])} h "
                f"({ordered['mae'].iloc[-1]:.3f}). Error should grow with lead time, so this is "
                "flagged rather than presented as a result."
            )
    lines.append("")

    lines.append("## Retrieved rows by variable, lead time and model")
    lines.append("")
    lines.append(_table(availability_report(forecasts)))
    lines.append("")

    lines.append("## Pairs by variable, lead time and truth source")
    lines.append("")
    counts = (
        pairs.groupby(["variable", "lead_time_hours", "truth_source"], observed=True)
        .size()
        .reset_index(name="pairs")
    )
    lines.append(_table(counts))
    lines.append("")

    lines.append("## Raw NWP error, station truth only")
    lines.append("")
    lines.append(_table(score(station_pairs, ["variable", "lead_time_hours", "model"])))
    lines.append("")

    lines.append("## By season")
    lines.append("")
    lines.append(_table(score(station_pairs, ["variable", "lead_time_hours", "season"])))
    lines.append("")

    lines.append("## By hour of day (UTC), day-ahead only")
    lines.append("")
    day_ahead = station_pairs[station_pairs["lead_time_hours"] == 24]
    lines.append(_table(score(day_ahead, ["variable", "hour_utc"])))
    lines.append("")

    irradiance = pairs[pairs["variable"].isin(IRRADIANCE_VARIABLES)]
    lines.append("## Irradiance by clear-sky regime")
    lines.append("")
    if irradiance.empty:
        lines.append("_No irradiance pairs._")
    else:
        labelled = clear_sky_index(irradiance, config)
        labelled = labelled[labelled["sky_regime"].notna()]
        lines.append(
            f"All rows in this table are {caveat}. The HungaroMet 10-minute export carries "
            "no radiation channel, so no in-situ irradiance is available for this point."
        )
        lines.append("")
        lines.append(_table(score(labelled, ["variable", "lead_time_hours", "sky_regime"])))
    lines.append("")

    REPORT_PATH.parent.mkdir(parents=True, exist_ok=True)
    REPORT_PATH.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {REPORT_PATH} ({len(pairs):,} pairs)")


def main() -> None:
    parser = argparse.ArgumentParser(description="Atlas forecast archive and verification.")
    parser.add_argument("--config", default="configs/atlas.yml")
    parser.add_argument("--refresh", action="store_true", help="Bypass the response cache.")
    sub = parser.add_subparsers(dest="command", required=True)

    backfill = sub.add_parser("backfill", help="Pull Previous Runs history.")
    backfill.add_argument("--start")
    backfill.add_argument("--end")

    live = sub.add_parser("live", help="Append the forecast as issued now.")
    live.add_argument("--forecast-days", type=int, default=4)

    verify = sub.add_parser("verify", help="Pair with truth and write the report.")
    verify.add_argument("--kind", default=None, help="Limit to one collector (backfill or live).")

    args = parser.parse_args()
    config = load_config(args.config)
    {"backfill": command_backfill, "live": command_live, "verify": command_verify}[args.command](
        config, args
    )


if __name__ == "__main__":
    main()
